# =======================================================
# force restart all servers, killing all processes
# =======================================================

# kill all quake instances
0001_os->kill = taskkill /F /IM Quake_x64_steam.exe /T

# moving files: double quotes around each parameter, and double backslashes for directories. <TIMESTAMP> gets replaced with a timestamp
# 0002_os->cmd = cmd.exe /c move "C:\\Users\\games\\Saved Games\\Nightdive Studios\\Quake\\stderr.txt" "C:\\Users\\games\\Saved Games\\Nightdive Studios\\Quake\\stderr_<TIMESTAMP>.txt" 
# 0003_os->cmd = cmd.exe /c move "C:\\Users\\games\\Saved Games\\Nightdive Studios\\Quake\\stdout.txt" "C:\\Users\\games\\Saved Games\\Nightdive Studios\\Quake\\stdout_<TIMESTAMP>.txt"

# set max number of players
# 0004_setMaxPlayers->val = 4

# set game mode
# 0005_setGameModeIndex->val = 2

# for launching quake: no double quotes around, but do use double backslashes for directories
0006_quake->launch = C:\\Program Files (x86)\\Steam\\steamapps\\common\\Quake\\rerelease\\Quake_x64_steam.exe -skipmovies +g_showintromovie 0 +developer 1

# execute a config: 
# - put a file named qelauncher.cfg in C:\Users\<user>\Saved Games\Nightdive Studios\Quake 
# - this will re-focus the Quake window using the command passed to it, and then exec the config. Don't include any parameters
# 0007_exeConfig->focus = C:\\Program Files (x86)\\Steam\\steamapps\\common\\Quake\\rerelease\\Quake_x64_steam.exe